export var engineMaxImpulse = 60;
export var distanceBetweenMeBodies = 20;
export var baseImpulse = 15000;
export var maxImpulse = engineMaxImpulse * 0.7;
export var firstAcellMultiplier = 2;
export var bulletSpeed = 10000;
export var pit_location = { x: 6560, y: 0 };
export var jumpImpulseY = 130000;
export var jumpImpulseX = jumpImpulseY * 0.2;
export var mapLimitX = 14080;
export var screenPadding = 1000;
//# sourceMappingURL=constants.js.map